version: "3.8"
services:

  api-database:
    image: postgres:12.3
    networks:
      - url-shortener
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always

  api-adminer:
    image: adminer:4.7
    networks:
      - url-shortener
    ports:
      - 8080:8080
    restart: always

  api-node:
    image: api-node
    build: .
    networks:
      - url-shortener
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    env_file: ./.env
    command: "wait-for-it.sh --strict api-database:5432 -- npm start"
    depends_on:
      - api-database
    restart: always

networks:
  url-shortener:
    external: true
